services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rynds-api
    restart: unless-stopped
    expose:
      - "3002"
    volumes:
      - /home/roniserv/Music:/app/music:ro
      - ./storage:/app/storage
    networks:
      - rynds-net

  nginx:
    image: nginx:stable-alpine
    container_name: rynds-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - rynds-net

networks:
  rynds-net:
    driver: bridge
